"""fix practice and mood

Revision ID: 2156ca0466a4
Revises: c6914140b792
Create Date: 2025-11-29 19:44:58.462126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2156ca0466a4'
down_revision: Union[str, Sequence[str], None] = 'c6914140b792'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('practices_mood_id_fkey'), 'practices', type_='foreignkey')
    op.drop_column('practices', 'mood_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('mood_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('practices_mood_id_fkey'), 'practices', 'moods', ['mood_id'], ['id'])
    # ### end Alembic commands ###
