"""add category to video

Revision ID: fcafc2750cbb
Revises: 24ad38da7f2c
Create Date: 2026-03-01 20:14:48.234872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcafc2750cbb'
down_revision: Union[str, Sequence[str], None] = '24ad38da7f2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('category', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'category')
    # ### end Alembic commands ###
