"""add MiniPractice model

Revision ID: 2467fe45b530
Revises: cb00106a183a
Create Date: 2026-02-10 19:16:18.278937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2467fe45b530'
down_revision: Union[str, Sequence[str], None] = 'cb00106a183a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mini_practices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.String(length=255), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mini_practices')
    # ### end Alembic commands ###
