"""clear models

Revision ID: 5a567b553ba9
Revises: de39a7f669ea
Create Date: 2026-03-07 14:30:44.547460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a567b553ba9'
down_revision: Union[str, Sequence[str], None] = 'de39a7f669ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('emotions')
    op.drop_table('user_achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('achievements_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('condition_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('condition_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='achievements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_achievements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('achievement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('user_achievements_achievement_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_achievements_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_achievements_pkey'))
    )
    op.create_table('emotions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emotion_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('emotions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('emotions_pkey'))
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', postgresql.ENUM('article', 'music', 'practice', name='favoriteitemtype'), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('favorites_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('favorites_pkey'))
    )
    # ### end Alembic commands ###
