"""add video file id to practice

Revision ID: 24ad38da7f2c
Revises: 049be6ad2646
Create Date: 2026-03-01 18:23:42.316824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24ad38da7f2c'
down_revision: Union[str, Sequence[str], None] = '049be6ad2646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practices', sa.Column('video_file_id', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practices', 'video_file_id')
    # ### end Alembic commands ###
