"""add caption to video

Revision ID: 38d79399a83e
Revises: 4d1c9f5a2b7c
Create Date: 2026-03-10 18:41:25.000319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d79399a83e'
down_revision: Union[str, Sequence[str], None] = '4d1c9f5a2b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('caption', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'caption')
    # ### end Alembic commands ###
