"""add Text prem

Revision ID: de39a7f669ea
Revises: bf520e3a22d8
Create Date: 2026-03-04 19:40:40.353079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de39a7f669ea'
down_revision: Union[str, Sequence[str], None] = 'bf520e3a22d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('texts', sa.Column('premium', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('texts', 'premium')
    # ### end Alembic commands ###
