"""add sections

Revision ID: 9232ee6ac878
Revises: 65fe9db21948
Create Date: 2026-03-07 20:57:09.991093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9232ee6ac878'
down_revision: Union[str, Sequence[str], None] = '65fe9db21948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('section', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('category_1', sa.String(length=500), nullable=True))
    op.add_column('products', sa.Column('category_2', sa.String(length=500), nullable=True))
    op.add_column('user_entitlements', sa.Column('section', sa.String(length=100), nullable=True))
    op.add_column('user_entitlements', sa.Column('category_1', sa.String(length=500), nullable=True))
    op.add_column('user_entitlements', sa.Column('category_2', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_entitlements', 'category_2')
    op.drop_column('user_entitlements', 'category_1')
    op.drop_column('user_entitlements', 'section')
    op.drop_column('products', 'category_2')
    op.drop_column('products', 'category_1')
    op.drop_column('products', 'section')
    # ### end Alembic commands ###
