"""add_cascade_delete_to_practice_logs

Revision ID: 7c801f13c8f1
Revises: 2156ca0466a4
Create Date: 2026-02-07 13:46:35.413412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c801f13c8f1'
down_revision: Union[str, Sequence[str], None] = '2156ca0466a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('practice_logs_user_id_fkey'), 'practice_logs', type_='foreignkey')
    op.create_foreign_key(None, 'practice_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'practice_logs', type_='foreignkey')
    op.create_foreign_key(op.f('practice_logs_user_id_fkey'), 'practice_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
