"""remove user subscribed

Revision ID: 4d1c9f5a2b7c
Revises: 3aaf86dd9b3b
Create Date: 2026-03-09 15:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1c9f5a2b7c'
down_revision: Union[str, Sequence[str], None] = '3aaf86dd9b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscribed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
