"""add category to video

Revision ID: 1bd7426b4a7a
Revises: fcafc2750cbb
Create Date: 2026-03-04 18:03:13.289036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd7426b4a7a'
down_revision: Union[str, Sequence[str], None] = 'fcafc2750cbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('category_1', sa.String(length=500), nullable=True))
    op.add_column('music', sa.Column('category_2', sa.String(length=500), nullable=True))
    op.add_column('music', sa.Column('section', sa.String(length=500), nullable=True))
    op.drop_column('music', 'category')
    op.add_column('video', sa.Column('category_1', sa.String(length=500), nullable=True))
    op.add_column('video', sa.Column('category_2', sa.String(length=500), nullable=True))
    op.add_column('video', sa.Column('section', sa.String(length=500), nullable=True))
    op.drop_column('video', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('category', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('video', 'section')
    op.drop_column('video', 'category_2')
    op.drop_column('video', 'category_1')
    op.add_column('music', sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('music', 'section')
    op.drop_column('music', 'category_2')
    op.drop_column('music', 'category_1')
    # ### end Alembic commands ###
