"""add titles

Revision ID: 51466770cdaf
Revises: 2467fe45b530
Create Date: 2026-02-10 19:37:30.953804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51466770cdaf'
down_revision: Union[str, Sequence[str], None] = '2467fe45b530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mini_practices', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('music', sa.Column('title', sa.String(length=500), nullable=True))
    op.add_column('video', sa.Column('title', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'title')
    op.drop_column('music', 'title')
    op.drop_column('mini_practices', 'title')
    # ### end Alembic commands ###
