"""add Text

Revision ID: bf520e3a22d8
Revises: 1bd7426b4a7a
Create Date: 2026-03-04 18:55:28.827138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf520e3a22d8'
down_revision: Union[str, Sequence[str], None] = '1bd7426b4a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('category_1', sa.String(length=500), nullable=True),
    sa.Column('category_2', sa.String(length=500), nullable=True),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texts')
    # ### end Alembic commands ###
