"""add phone and email to user

Revision ID: 3aaf86dd9b3b
Revises: 159cfaa13dc1
Create Date: 2026-03-09 14:41:12.425704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aaf86dd9b3b'
down_revision: Union[str, Sequence[str], None] = '159cfaa13dc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
